### ISSUE TITLE
Can you get this to work?

### ISSUE THREAD

**Issue by sotiris-bos** [kvaps/kube-pipework#1]
I am trying to run both yours and dreamcat4's version of this and upon running, I get:

```
ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted
Device "eth1" does not exist.
```
 and pipework fails to add the eth1 interface to my test container.

I tried both on Centos 8 and Arch 5.3.8, Docker version 19.03.5-ce, build 633a0ea838

**Comment by kvaps** [comment]
Hi, yes, I'm using it pipework with bridges in Kubernetes. My cmdline is looking like:
 
```
docker run --privileged --pid=host --net=host \
  -v /var/run/docker.sock:/docker.sock \
  -e run_mode=batch,daemon \
  -e host_routes=true \
  -e route_add_delay=1\
  kvaps/pipework:v1.0.0
```

I think you're specified pipework_cmd wrong, `eth1` - it is host interface.

**Comment by sotiris-bos** [comment]
Thanks for the reply. I have tried on 4 distros with two different docker versions now, none of them worked.

That is how I am using it as well. `eth1` is the container interface that pipework tries to create and fails, not the host interface.

Would you mind sharing your docker and containerd versions?

**Comment by kvaps** [comment]
Sure, I have Arch Linux with docker `19.03.5-ce, build 633a0ea838`
and `Ubuntu 18.04.2 LTS` with  `Docker version 19.03.5, build 633a0ea838`

Please show me your `pipework_cmd` line

**Comment by sotiris-bos** [comment]
Thanks again for your reply!

I have tried with `pipework_cmd=eno1  test_myapp_1 dhcp` and `pipework_cmd= direct-phys eno1v2 test10 10.0.10.240/24` to pass an SR-IOV VF through and many other permutations with both `docker run` and `docker-compose`. Interface and container names were correct at all instances.

I tried on Arch 5.3.8 and Centos 8 with `19.03.5-ce, build 633a0ea838` and Ubuntu 18.04 and 16.04 with `18.09.7`  docker.io apt packages.

On all occasions, I get the cgroup error I mentioned in the first post. I feel like pipework is not able to create the `ethX` interface in the test containers for some reason. I will run the pipework container with debug mode and report back with all commands and outputs as soon as I can.

**Comment by kvaps** [comment]
I have this error too, but pipework is working for me.

BTW, this error was mentioned for dreamcat4/pipework even 3 years ago:
https://github.com/dreamcat4/docker-images/issues/12#issuecomment-139152271

**Comment by sotiris-bos** [comment]
OK, I got it to work with static IPs but DHCP does not work at all.

Have you tried with DHCP?

**Comment by kvaps** [comment]
I was trying long time ago, it was working with bridges, I think DHCP will not work in macvlan mode

**Comment by sotiris-bos** [comment]
OK I tried manually running pipework with `--direct-phys` option and `dhclient` and it works.

```
./pipework --direct-phys eno1v0 a5eea2eac14d dhclient
```

Any idea why the `--direct-phys` option does not work with the docker pipework and `pipework_cmd` ?

**Comment by sotiris-bos** [comment]
After much troubleshooting:

1. `ln: failed to create symbolic link '/sys/fs/cgroup/systemd/name=systemd': Operation not permitted` does not seem to affect anything

2. DHCP does not seem to work with macvlan for the time

3. The `--direct-phys` option to assign full physical or SR-IOV virtual interfaces had not been implemented by dreamcat4. After much help from them it has now been implemented and is working: https://github.com/dreamcat4/docker-images/issues/46

I am going ahead and closing the issue.
